### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by anja225** [axa-ch/style-guide#101]
Please have a look at the grey bar from the footer.

webcharta
http://axa.sandbox.comptoirsduweb.com/public/blank.html

Bar height: 25px
Bar color: #e5e5e5
Bar Font color: #79838d
(Both colors are defined colors)

Footernavigation and copyright is right-aligned.

**Comment by davidknezic** [comment]
![flat_desktop_produkt](https://cloud.githubusercontent.com/assets/198988/9610126/e524245e-50d7-11e5-8953-e4923a98d8a8.png)
![home_flat](https://cloud.githubusercontent.com/assets/198988/9610137/eda38426-50d7-11e5-956d-5048afb8dc96.png)

**Comment by davidknezic** [comment]
This will be resolved by #342
