### ISSUE TITLE
Button Dropdowns

### ISSUE THREAD

**Issue by muellermike** [axa-ch/style-guide#156]
How about Button Dropdowns?
For example:
http://getbootstrap.com/components/#btn-dropdowns

Use-case:
Some actions which belong to one 'resource' can be grouped within a button dropdown:
![image](https://cloud.githubusercontent.com/assets/7766762/5857002/623d4432-a248-11e4-82a4-4e4c16823bbb.png)

**Comment by davidknezic** [comment]
in progress in #325
