### ISSUE TITLE
Styleguide 😖

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#244]
Whenever I see `styleguide` (or worse `Styleguide`) in our docs it fills me with horror. 😖
Since we're building this whole thingy in proper English language we have to rename the probably most important name in our docs to `style guide` or `Style Guide`.

* This is a great **style guide**.
  * 👉 when we talk about style guides in general
* Our **Web Style Guide** is awesome!
  * 👉 when we talk about our style guide

**Comment by davidknezic** [comment]
It's decided and we can officialy go with `Web Style Guide`. This is already in progress in #331.

**Comment by elessar-ch** [comment]
Yaaayyy!!! This has been implemented in version 0.7.0.
