### ISSUE TITLE
Have every PR built and served for testing

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#254]
When I build a block or write some docs and I want design or ux to see it I have to show them on my laptop. How about having every PR built and hosted automatically, sur la cloud!

`feature/button-dropdown` :point_right: `http://foobar/feature/button-dropdown`

Azure has an API and we have monthly credit left. What do you think? Next sprint?

**Comment by davidknezic** [comment]
Duplicate of #318

**Comment by elessar-ch** [comment]
Further discussions and tracking through #318
