### ISSUE TITLE
Move to travis ci

### ISSUE THREAD

**Issue by sventschui** [axa-ch/style-guide#290]
Now we're open source we could move to travis, @davidknezic ?

**Comment by davidknezic** [comment]
Do you think it's better than Shippable?

**Comment by sventschui** [comment]
Well the shippable app kinda lags and the fact to have to log in every time you open their page is awful.

Travis seems to provide the better UX overall.

**Comment by sventschui** [comment]
Travis build runs in 1 min 47 sec, whereas shippable took 4 to 9 minutes

**Comment by davidknezic** [comment]
Let's go for it! :+1:

**Comment by davidknezic** [comment]
This issue is closed by #292.

**Comment by davidknezic** [comment]
Automatic deployment didn't work, so I tried to fix it by using the right ENV variables in c44e46770e4e68861488cf55ca51e0adf0b1fe84. But there are still problems since Travis lacks the private Key for GH deployments.

**Comment by davidknezic** [comment]
Fixed this with a68bcecb1f990b5b3afdcac093a35f2e829f85b5.
