### ISSUE TITLE
Search filters common words (and, but, or)

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#296]
When you search for `bu`, the autocomplete will deliver:

* Button
* Primary Button
* Radio Buttons
* ...

... but when you continue with `but` you'll get no results.

Apparently common words are filtered. (e.g. and, but, or, ...)

**Comment by digisz** [comment]
@davidknezic maybe problem with the stopWordFilter function in lunr... (had a file popping up in one of my local searches with thename stop_Word_Filter.js)

**Comment by sventschui** [comment]
Yes it is definitly related to the stop word filter in lunr. See http://lunrjs.com/docs/#stopWordFilter
