### ISSUE TITLE
Value change not handled by segmented control

### ISSUE THREAD

**Issue by richiew** [axa-ch/style-guide#337]
If the value of a segmented control is set by javascript, the style is not adapted accordingly. The correct radio input element is checked, but the style is not updated.

**Comment by richiew** [comment]
E.g. navigate to the styleguide implementation of the segmented control, open the console and enter $('.segmented-control__item__radio',$('#iFrameResizer0').contents())[0].checked = "checked";
--> nothing happens. Even triggering change events seems not to help. The change event in segmented-controls.js is not fired.

**Comment by sventschui** [comment]
> Even triggering change events

That part was surprising...

Have you used a regular event or a jQuery event?

**Comment by richiew** [comment]
We should check together the issue in the adaptive forms where we implemented the segmented control. There the mentioned workaround is not working.

**Comment by sventschui** [comment]
Well that's not really a workaround. Problem with changing the value by JS is that the browser (intentionally) doesn't emit a change event, you have to do that on your own, if you want to. (Be aware of infinite loops, that's why the browser doesn't do it). Emitting a raw JS event is quite tricky, therefore if you're using jquery already (what you have to, to be able to use the style guide) you should simply use the jquery `change` method

**Comment by richiew** [comment]
I will check it with @davidknezic 

We are not able to 100% reuse the styleguides code as there are some fragments needed by AEM AF to ensure the controls functionality (e.g some enclosing divs). Further we have to rely on a guideBridge (implemented in jQuery) for value changes on elements. Therefore it is better to check the problem together in the AF form as it does not offer the "perfect environment" of the style guide ;)

Until now we were able to get most of the elements running, but the radiobutton/segmented control is making headache since some weeks. Therefore someone of your team has to check with us the integration in AEM forms. Maybe there as to be changed something in the style guide, maybe we can implement anything to get it running without affecting the style guide. But we need your support.

**Comment by elessar-ch** [comment]
@richiew We'll have a look at it this week.

**Comment by sventschui** [comment]
The style guide must not be affected by framework / platform restrictions, as mentioned in #343 before. @davidknezic and/or @elessar-ch may assist you on getting it running within aem forms

**Comment by richiew** [comment]
@elessar-ch Thank you very much for the feedback. I would appreciate if we could check this (and other integration issues) together as soon as possible. I'm in Winterthur Tuesday and Wednesday. Dragana is informed about some of the issues as well. She should be available 100%.

**Comment by richiew** [comment]
@sventschui Thank you for your feedback. Until now we face many problems with integrating the style-guide and have to do "hacks" to get it working. Unfortunately the environment we are working with is not as perfect as the style-guide assumes ;-) But we will check the contacts you mentioned what needs to be done for getting the styles working.

**Comment by elessar-ch** [comment]
I had a look at this with @richiew. It's a problem of how it was used with the frameworks of the target solution. We could find a solution.
