### ISSUE TITLE
Segmented control: stacked style is applied even if enough space is available

### ISSUE THREAD

**Issue by richiew** [axa-ch/style-guide#345]
When using the segmented control for the salutation, the elements get stacked even if there is enough space to arrange them side by side:

Rendering:
![kontaktformular](https://cloud.githubusercontent.com/assets/13537848/9718514/c7ac447a-557c-11e5-9afc-7ca802104650.png)

Source:
![kontaktformular](https://cloud.githubusercontent.com/assets/13537848/9718521/e5136304-557c-11e5-9921-81f079ec2abd.png)

**Comment by sventschui** [comment]
what does it look like when you drop the `segmented-control--stacked` modifier in the dev tools?

**Comment by richiew** [comment]
When I remove the modifier with the Chrome dev tools the result is as follows:

Rendering:
![kontaktformular](https://cloud.githubusercontent.com/assets/13537848/9718622/b82e8df4-557d-11e5-8703-f010ae11e09b.png)

Source:
![kontaktformular](https://cloud.githubusercontent.com/assets/13537848/9718638/d0129622-557d-11e5-9f2d-c6802af649df.png)

**Comment by sventschui** [comment]
weird. I think there is an error when calculating the width of the segmented control or its container. Is there a possiblity I can have a look at the page you're refering to? So I could debug in the segmented control plugin

**Comment by richiew** [comment]
I should be able to provide you tomorrow with an URL where you can check this issue.

**Comment by elessar-ch** [comment]
Close this in agreement with @richiew. It was a problem with applying the markup in forms.
