### ISSUE TITLE
Add BaconJS as Web Style Guide dependency

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#354]
I recently started to build as many interactions as possible as streams. This helps reduce state and makes it possible to have everything under control. For that I used BaconJS.

The first place I added this was in the example jquery plugin in the `responsive-all-over-again` branch. That's okay, because the user of the Web Style Guide doesn't really notice there's another dependency.

Now I found that the `collapse` plugin could also use some streams to be more maintainable. This however introduces a new dependency for our users, the BaconJS dep!

@elessar-ch @sventschui What do you think? Is it reason enough to introduce this one?

* [docs/js/example.coffee](https://github.com/axa-ch/style-guide/blob/improvement/responsive-all-over-again/docs/js/example.coffee) in `improvement/responsive-all-over-again`
*  [jquery/collapse.js](https://github.com/axa-ch/style-guide/blob/feature/collapsible/jquery/collapse.js) in `feature/collapsible`

**Comment by sventschui** [comment]
:+1: go for it

As already discussed on slack we should not have the static functions (scan, map, ...) as methods.

**Comment by davidknezic** [comment]
Nice, seems we're using it all over the place now! Closing this.
