### ISSUE TITLE
page not clickable on ie10 (site__page__mask) 

### ISSUE THREAD

**Issue by flavaflo** [axa-ch/style-guide#401]
what is the empty `<div class="site__page_mask"/>` doing ontop of the page. the page is not usable because of this overlaying div...

<img width="1426" alt="axa-styleguide-site_mask-ie10" src="https://cloud.githubusercontent.com/assets/1135375/11238128/e8d9c916-8de3-11e5-92c2-41af69dc32fd.png">

**Comment by flavaflo** [comment]
pointer-events: none is not supported on IE10

**Comment by davidknezic** [comment]
true, will have to find an alternative solution, maybe `display: none` for IE10. That way we won't be able to animate the masks background, but hey, it's IE anyway.
