### ISSUE TITLE
Final decision: To IE9, or not to IE9

### ISSUE THREAD

**Issue by sventschui** [axa-ch/style-guide#409]
We should finaly decide wether to support IE9 or not, since various question depend on this decision.

We should consider:

- CORS won't work on IE9, and our API runs on a different domain than our customer portal / website
  - The new customer portal will therefore not support IE9
- Flexbox support is awful and no useful Polyfill is available
- We finally moved to IE11 and more companies will in the near future

@davidknezic @digisz @elessar-ch I'd recommend to drop IE9 support. See also the Google Analytics Screenshot on slack 

Update @davidknezic

* [ ] Introduce *bye bye* IE9 information overlay

**Comment by digisz** [comment]
So. From an UX perspective, there is no more justification for IE9. 

Business details in Slack.

So for now I recommend dropping it in a human way. Display an overlay to IE9 users which informs them about the incompability. After that, they should still be able to open the page, but they have been warned.

**Comment by davidknezic** [comment]
* [ ] Introduce *bye bye* IE9 information overlay

**Comment by davidknezic** [comment]
I think we solved that one. 😃
