### ISSUE TITLE
Fix the main menu

### ISSUE THREAD

**Issue by elessar-ch** [axa-ch/style-guide#416]
![image](https://cloud.githubusercontent.com/assets/7779684/11444962/a2aa8786-9528-11e5-9364-3f67a8a7cf26.png)

'nuff said

**Comment by elessar-ch** [comment]
@davidknezic is it a simple z-index problem or did you have another solution in mind?

**Comment by davidknezic** [comment]
http://latest.design.axa.ch/inspiration/pages/test.html

**Comment by AndyOGo** [comment]
@davidknezic @elessar-ch 
Is this still up to date? Or can it be closed?

**Comment by davidknezic** [comment]
I think we fixed this. Will close. Should it happen again, let's create a better issue.
