### ISSUE TITLE
Bower doesn't work with current version

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#439]
@TheDadi found out that our current version doesn't work with Bower. It's because bower gets the repository and doesn't build the style guide. That's why some of our less files still have the `.lodash` suffix.

**Comment by davidknezic** [comment]
How about getting rid of lodash templating in our less files (it's only `variables.less.lodash`)? We could include the colors and write something fancy to extract the values for our docs,

**Comment by sventschui** [comment]
We could write a small (project scoped) metalsmith plugin to extract the variables from the less file

**Comment by davidknezic** [comment]
yes, it wouldn't be the first one `lib/metalsmith-*.js`. when are you going to finish it? :smile:

**Comment by davidknezic** [comment]
Should be resolved now...
