### ISSUE TITLE
jQuery plugins don't have destruction/cleanup functionality

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#468]
I'm currently build a React Component to for dropdown, to utilize our jQuery plugin.
Construction is no problem, but as soon as my component unmount I need to cleanup the markup which is not controlled by React directly.

In case of dropdown, the bound events should be properly unbound.

**Comment by sventschui** [comment]
Rewrite to React instead? Much easier, much 😎

**Comment by AndyOGo** [comment]
Indeed.
Though we should code our jQuery Plugins properly, especially regarding possibly memory leaks.
