### ISSUE TITLE
Modal is pre-rendered and should be encapsulated from a Dialog

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#482]
Shouldn't modal html be rendered by JS on the client only on demand?
I would also always place modal markup at the bottom of `<body>`, not anywhere in the whole page - to avoid z-index and html-flow issues.

And so far we have a modal dialog implemented.
I would separate those two components, so that the `dialog` markup is wrapped inside an `modal` block.
And inside a `modal` any component could be viewed in a modal manner.

As I can see at the moment we don't manage the occurrence of multiple modals properly, or parent/child modals, etc.

Compatibility with React, Angular, etc is a concern too.

**Comment by davidknezic** [comment]
The split of modal and dialog would make sense!

The reason we pre-render the whole modal/dialog: That way the rendering of the markup can be done by the CMS or app directly. You're less limited by what the js supports.

Occurence of multiple dialogs or parent-child ones isn't handled properly, that is correct.

**Comment by AndyOGo** [comment]
Hey dave, thx for your quick feedback.

I see, that approach also eases i18n.

So I think we need modals which can open from different data sources, like:

- CMS inline pre-rendered markup
- Complete HTML page requested by AJAX
- JS templates
- React-Component
- Angular Directive

But which of those should be supported by the style-guide and which would be application-specific, like React, Angular support.

I would favour a generic solution which should also work in between of jQuery/DOM land and React.
That gonna be complex, I'm sure...

**Comment by AndyOGo** [comment]
Okay we (me and @anja225 ) started to sit down and think about needed features.
The following is the feature request we came up with:

*Design*
- [ ] Full page Overlay / Dimmer
- [ ] Background
- [ ] Close Feature
 - [ ] Close-Icon
 - [ ] Click outside modal content

*Content*
It should be possible to display any content, though we concentrate on the following concrete use cases:
- [ ] load a given page via AJAX and display it (like agent-page, contact, page-lists, etc.)
- [ ] Dialog (separate feature)

**Comment by anja225** [comment]
@sventschui Please have a look at our current specifications and give us feedback if you need anything special for myAXA.

**Comment by sventschui** [comment]
In myAXA we use a bottom sheet (on mobile) that features a cancel action instead of a close button. Would be nice to be able to use the modal (but not dialog). Therefore :+1: on separation of concerns.

Desktop: 
![image](https://cloud.githubusercontent.com/assets/512692/17727075/20f47cde-6457-11e6-89f2-482aa8925384.png)

Mobile: 
![image](https://cloud.githubusercontent.com/assets/512692/17727091/36f3c774-6457-11e6-9d68-0db190c3e655.png)

We also feature very different sizes of dialogs. Very small (insurance provisions download popup) or quite large (contact / consultants).
