### ISSUE TITLE
normalize.less file doesn't reset important tags / CSS properties consistently across browsers

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#487]
ATM we don't provide default styles for tags like `p`, `h1` to `h6`, HTML5 tags, etc.
I think it is really important to reset these styles.

This leads to user-agent style-sheets being in use if we don't have a BEM block for it.

I'm concerned especially about dimensions (padding, margin), various states and such stuff.
See attached screen:

<img width="1337" alt="screen shot 2016-07-12 at 14 15 46" src="https://cloud.githubusercontent.com/assets/914443/16766553/3029494c-483b-11e6-8a6f-559b7fece264.png">

**Comment by sventschui** [comment]
There is already a normalize.less file in /less?!

**Comment by AndyOGo** [comment]
yes but it doesn't do that

**Comment by AndyOGo** [comment]
@davidknezic and me decided to leave `normalize.less` as is and to introduce a new file called `reboot.less` which adds generic styles according to AXA Designs.

**Comment by davidknezic** [comment]
Reasons for that decision:

* we don't touch the `normalize.less` file and can update it
* we do it the same way as Bootstrap 4 does
