### ISSUE TITLE
LESS user defined functions

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#489]
I find it pretty cool to have the ability for user defined functions like `pixelToRem`or other low level or value centric stuff.

I found three possible solutions:

1.  Backticks Hack
see: https://github.com/less/less.js/issues/637#issuecomment-19445138
or: https://github.com/less/less.js/issues/637#issuecomment-168301542
see: http://www.bennadel.com/blog/2638-executing-javascript-in-the-less-css-precompiler.htm
2. NPM plugin (which I don't like that much)
https://www.npmjs.com/package/less-plugin-functions
3. `@plugin` directive

**Comment by AndyOGo** [comment]
@sventschui @elessar-ch 
Any feedback? Would you need custom functions in less, e.g. `pixelToRem`.
Or could you live without it?

**Comment by davidknezic** [comment]
One tradeoff that this introduces, is the need to adjust the build slightly (feed the gulp plugin with `*.js` files too).

**Comment by AndyOGo** [comment]
Since we switched to SASS this obsolete and we got sass functions now
