### ISSUE TITLE
Where's the favicon?

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#49]
Not a killer, but we'll have to bundle that with the style guide. And when we have a favicon we could reference it in the docs, so I can find the style guide tab faster in my Chrome tab jungle.. :laughing: 

![favicon](https://cloud.githubusercontent.com/assets/198988/4795073/70e35d84-5df9-11e4-84ea-985c2c3ebb73.PNG)

**Comment by sventschui** [comment]
The style guide includes app icons and a favicon (Tested in FF@OSX, Chrome@OSX and IE 9). Therefore closing this
