### ISSUE TITLE
Add meta-language2 from beta.axa.ch to the style guide

### ISSUE THREAD

**Issue by sventschui** [axa-ch/style-guide#517]
Could someone please add the meta-language2 from the beta.axa.ch to the style guide? Thanks!

**Comment by AndyOGo** [comment]
The JS-Part is actually build with React.
But I want the style-guide staying free of frameworks. I'm sure you would the React code too?

**Comment by sventschui** [comment]
Yes we need the react stuff too. Again React vs JQuery Plugins 😂 @davidknezic

**Comment by AndyOGo** [comment]
Okay, I think we have two options:

- Either create an react folder und put react stuff there (quick and dirty)
- Or create a separate React repo which depends on style-guide (clean and costly)

**Comment by sventschui** [comment]
I'd incorporate the react stuff in here. Everybody that wants to use it can require it and everybody else can just leave it :)

**Comment by AndyOGo** [comment]
okidok, will add a react folder

**Comment by sventschui** [comment]
Thank you 🍻
