### ISSUE TITLE
Bring back latest.design.axa.ch

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#552]
Seeing how much is hapening here, thought it might be helpful to bring back https://latest.design.axa.ch.

**Comment by davidknezic** [comment]
Done.

Make sure the image builds on Docker hub. If you want it deployed just upgrade `web-style-guide-latest`.

<img width="1117" alt="screen shot 2016-08-19 at 10 52 51" src="https://cloud.githubusercontent.com/assets/198988/17819090/32060fba-65fb-11e6-9fb6-e9f0251839b1.png">

Regards from Santa Maria, CA.

**Comment by AndyOGo** [comment]
Hey hey dave,

enjoy your holidays.
Du nerd, du schaffst auch im urlaub 😀 

lg andy
