### ISSUE TITLE
Mobile: Datepicker click Icon does not trigger native control

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#555]
The native control should open upon click on icon and input field.

![datepicker-mobile-click-icon](https://cloud.githubusercontent.com/assets/914443/17932913/5fe7e488-6a12-11e6-88a2-f66757d4dde1.gif)

**Comment by sventschui** [comment]
Already had a look at this issue.

You can get that to work on desktop envrionements by simulating a click event but that won't work on mobile. I think this issue is not solvable that easy

**Comment by sventschui** [comment]
Just saw this SO: http://stackoverflow.com/a/29998684/2164347

Maybe it works on newer android versions by simulating a click. It didn't work for me though

**Comment by AndyOGo** [comment]
As I know it would not work with synthetic events, but if it is triggered through a human initiated event it should work. At least i hope so...

**Comment by AndyOGo** [comment]
lets see if a simple focus does the trick

**Comment by AndyOGo** [comment]
Okay. `.focus().click()` does not seem to work.
I think only of another hacky workaround by creating a second transparent `<input type="data">`, which will be absolutely positioned above the icon, will receive the human created click event, then shows the native date picker, onchange updates the visible data input field.

I know it's crazy, though I'm sure it will work - like the infamous checkbox hack...
