### ISSUE TITLE
Refactor Build, kill gulp

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#583]
I think the biggest problem we have with our current build setup is speed

## TL'DR

Drop | Replacement
--- | ---
Browserify | WebPack
Gulp | NPM scripts
MetalSmith | Hugo
Less | LibSass

## Status Quo

- MetalSmith is our slowest fellow
- Browserify is very slow too
- Less
- Another main problem are Gulp-Plugins, which are just wrappers around real implementations

Since we are currently trying allot to improve this situation ( #572 #570 ).
I found it's time to consider to drop gulp. Personally I would favour make, but since this can be problematic here, I googled around and found this awesome post, about [npm as a build tool](https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/)

## The WebPack `~` tilde non-standard hack

I'm really convinced that we should utilize webpack to build our JS.
But webpack really fails if one want to require other assets (styles, images, etc.) from other modules. One would need to use `~`-prefix and can't utilize options which come out of the box from less (like [`--include-path`](http://lesscss.org/usage/#command-line-usage-options), `--root-path`, ...), same with sass.

It is a underlying [design fault introduced by webpack's creator](https://github.com/webpack/less-loader/issues/74#issuecomment-201847685)

There is a possible workaround with https://github.com/bholloway/omit-tilde-webpack-plugin

Very likely that your IDE can't resolve those files anymore and will lint false positives.

## Feature Request

- Module Bundling (incl. transpilation, uglifying, ...)
- Icon Sprite Generation
- Automatic Documentation (incl. JSDoc)
- Incremental Builds - file watchers
- BrowserSync / Hot Module Reloading - check https://www.npmjs.com/package/browser-sync-webpack-plugin or https://www.npmjs.com/package/webpack-hot-middleware
- Prod vs Dev setups

**Comment by AndyOGo** [comment]
**Vote WebPack only for JavaScript**

**Comment by davidknezic** [comment]
I'm actually rethinking my vote for WebPack only with JS!

It's very easy to build our SVG sprite and CSS with WebPack too. Also it saves us from building a watch-recomplile-livereload process for SVG and CSS, because the WebPack dev server handles hot reloading already.

**Comment by AndyOGo** [comment]
@davidknezic 
In an ideal world I would definetly agree, but as far as I know there is no plan/willingness from webpacks creator to fix this basic design issue.

Did you check if the `omit-tilde-weback-plugin` works for us?

We can still utilise HMR for JS by [webpack hot middleware](https://www.npmjs.com/package/webpack-hot-middleware), which can be loaded into browsersync.
Anyway we will need an instance of livereload/browsersync for the docs pages.

**Comment by elessar-ch** [comment]
I think  this discussion is settled with our recent refactoring. Do you agree @AndyOGo @davidknezic ?

**Comment by AndyOGo** [comment]
absolutely

**Comment by davidknezic** [comment]
yes
