### ISSUE TITLE
Integrate Franklin Gothic Font

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#594]
Since we recently integrated the franklin gothic font into axa.ch and myaxa before.
I thought it would make sense to have it bundled in the styleguide.
What do you think?

**Comment by sventschui** [comment]
We're not allowed to bundle it within the style guide because of the licensing

**Comment by AndyOGo** [comment]
thanks, thats clear enough ©️ ™️

**Comment by davidknezic** [comment]
we're going to get better and open fonts anyway soon 🎉
