### ISSUE TITLE
Uncaught TypeError: this.$modal.asEventStream is not a function

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#606]
Somehow `asEventStream` is not available on a jQuery collection for axa.ch, though it works at design.axa.ch 😮 

> Uncaught TypeError: this.$modal.asEventStream is not a function

Reapply @davidknezic fix from https://github.com/axa-ch/style-guide/releases/tag/v0.12.4

**Comment by davidknezic** [comment]
It probably works on design.axa.ch, because we shim Bacon and jQuery in the build and include them using a CDN. When these libs are included using `<script>` tags, they inject studd into each other.
