### ISSUE TITLE
Remove FOUC in dev mode

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#615]
Actually I don't have the full FOUC in Firefox, just in Chrome, Chrome Canary, Safari.

![fouc](https://cloud.githubusercontent.com/assets/914443/18828305/784023b8-83d7-11e6-9f48-8eab4365f886.gif)

Firefox seems to be a bit more clever. To clarify, I have to click very fast in FF to get the full FOUC:

![firefox-menu-flash](https://cloud.githubusercontent.com/assets/914443/18835902/c0b1a740-83fd-11e6-97d4-d6b97aca4e3d.gif)

SO entry:
http://stackoverflow.com/questions/36453826/how-to-stop-fouc-when-using-css-loaded-by-webpack

## Solutions

1. Either move webpack stuff for dev into the head section (so that it loads faster)
2. Or utilize the [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin)

**Comment by davidknezic** [comment]
I'm not quite sure if this is a FUOC issue. I think this happens since I extended the side bar with these new modifiers. #574 

The problem is that the side bar is expanded at first, until the JS loads and hides it. We should probably fix this by having the side bar hide itself by default, and pop open when a `.is-open` class is set.

**Comment by AndyOGo** [comment]
Even, that we can fix that slide. And maybe improve FOUC by putting the script above the bottom line 😃  and still get HMR for styles - what a wonderful world 🎉

**Comment by AndyOGo** [comment]
@davidknezic 
I invested the issue again more deeply, and I'm sure it is indeed a FOUC issue for the following reasons:

1. From what I see the side bar is already hidden by default
2. The things there is no CSS -> hence he renders the page
3. Then suddenly webpack lazy injects some CSS (in the meanwhile the browser has calcualted the default values of CSS properties)
4. By injecting the new CSS this starts a property change and the CSS transition gets kicked off

see SO for similiar issue http://stackoverflow.com/questions/14389566/stop-css3-transition-from-firing-on-page-load

**Comment by AndyOGo** [comment]
@davidknezic 
I will try to put stuff above the fold, if this remedies the FOUC I'm happy with it, if not I would rather utilize the `ExtractTextWebpackPlugin` and serve it with `BrowserSync`
