### ISSUE TITLE
Update Viewport meta tag

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#619]
Currently we just set `width=device-width` of the viewport meta tag.

I would definitely add `initial-scale=1.0` and `shrink-to-fit=no` (since iOS 9).

Then there is also the CSS `@viewport` rule, which i would consider:
https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport
https://msdn.microsoft.com/en-us/library/hh869615(v=vs.85).aspx

## Big Question
Do we want to disable or allow zooming?
Of course there are a lots of [UX factors](http://adrianroselli.com/2015/10/dont-disable-zoom.html)

IMHO this "allow zooming" works very well for plain content, and I agree it is especially useful for text and images.

Buuuut, as soon as some fancy JS comes into play, handling fancy touch events, this fancy JS will probably prevent the default actions, hence all the fancyness like zoom, horizontal/vertical scrolling will be lost for that section.
Ideally this fancy JS should implement stuff to copy this "allow zooming" thingy.

Common Example: [Google Maps](http://stackoverflow.com/questions/6397748/whats-the-point-of-meta-viewport-user-scalable-no-in-the-google-maps-api)...
For axa.ch we currently have this JS issue handling custom touch events in our forms, which implement a full page swipe to navigate to next/previous form panels inside AEM's forms wizard

We could disable Zoom by `user-scalable=no`, `minimum-scale=1.0`, `maximum-scale=1.0`.

**Comment by davidknezic** [comment]
My opinion on mobile browser zooming: I don't like it. Zooming often breaks pages, especially fix positioned elements like mobile drawers, sticky headers. However, there is @digisz who says that zooming on mobile is very essential for some people I personally never use it, because of my bad experience breaking pages with it.

Meaning that it doesn't matter for me whether we enable or disable it.

> For axa.ch we currently have this JS issue handling custom touch events in our forms, which implement a full page swipe to navigate to next/previous form panels inside AEM's forms wizard

On that point: How non-standard is that behavior? Nobody will ever do that! Especially because swiping left right is usually handled by the mobile browser to go back or forward in the history. I'd kill this feature, makes no sense to me.

**Comment by digisz** [comment]
Zooming is essentials, especially in the wcga 2.0 aa accessibility area

Non default behaviour: retarded

David Knezić <notifications@github.com> schrieb am Mi. 28. Sep. 2016 um
11:50:

**Comment by AndyOGo** [comment]
> On that point: How non-standard is that behavior? Nobody will ever do that! Especially because swiping left right is usually handled by the mobile browser to go back or forward in the history. I'd kill this feature, makes no sense to me. It's Adobe once again doing stuff they shouldn't.

So true, It's really annoying 😞

**Comment by AndyOGo** [comment]
@digisz 
Of course zooming would be great.
But a major fact this spec does not consider are interactive components, full page stuff, interactive maps, etc. Those collide heavily with browser's default zooming and in fact decrease user's experience if they break.

**Comment by AndyOGo** [comment]
Okidok, we quickly decided to disable zoom for axa.ch as long as the following stuff is not compatible:
* Google Maps
* Adobe Forms Wizard swipe
* fixed position elements
* and more
