### ISSUE TITLE
Sure the build is stable?

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#622]
Sometimes I get weird errors.
I normally try to `npm install` first, but all dependencies seem to be there.

Anyone getting such errors?

> [docs] [scss:copy] /Users/axawinterthur/dev/style-guide/node_modules/configstore/index.js:86
> [docs] [scss:copy] 	return this.all[key];
> [docs] [scss:copy] 	               ^
> [docs] [scss:copy]
> [docs] [scss:copy] TypeError: Cannot read property 'update' of undefined
> [docs] [scss:copy]     at Object.Configstore.get (/Users/axawinterthur/dev/style-guide/node_modules/configstore/index.js:86:17)
> [docs] [scss:copy]     at UpdateNotifier.check (/Users/axawinterthur/dev/style-guide/node_modules/update-notifier/index.js:51:28)
> [docs] [scss:copy]     at module.exports (/Users/axawinterthur/dev/style-guide/node_modules/update-notifier/index.js:127:17)
> [docs] [scss:copy]     at Object.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/sync-files/bin/sync-files.js:121:3)
> [docs] [scss:copy]     at Module._compile (module.js:413:34)
> [docs] [scss:copy]     at Object.Module._extensions..js (module.js:422:10)
> [docs] [scss:copy]     at Module.load (module.js:357:32)
> [docs] [scss:copy]     at Function.Module._load (module.js:314:12)
> [docs] [scss:copy]     at Function.Module.runMain (module.js:447:10)
> [docs] [scss:copy]     at startup (node.js:146:18)

**Comment by davidknezic** [comment]
oh, never had that one before! 😕 

If I get it, I'll tell you.

**Comment by davidknezic** [comment]
Well, I get this from time to time:

```
[docs] [images:copy] /Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/configstore/index.js:86
[docs] [images:copy]   	return this.all[key];
[docs] [images:copy]   	               ^
[docs] [images:copy]
[docs] [images:copy] TypeError: Cannot read property 'optOut' of undefined
[docs] [images:copy]     at Object.Configstore.get (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/configstore/index.js:86:17)
[docs] [images:copy]     at UpdateNotifier.check (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/update-notifier/index.js:47:18)
[docs] [images:copy]     at module.exports (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/update-notifier/index.js:127:17)
[docs] [images:copy]     at Object.<anonymous> (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/bin/sync-files.js:121:3)
[docs] [images:copy]     at Module._compile (module.js:413:34)
[docs] [images:copy]     at Object.Module._extensions..js (module.js:422:10)
[docs] [images:copy]     at Module.load (module.js:357:32)
[docs] [images:copy]     at Function.Module._load (module.js:314:12)
[docs] [images:copy]     at Function.Module.runMain (module.js:447:10)
[docs] [images:copy]     at startup (node.js:146:18)
```

**Comment by davidknezic** [comment]
Now I've got it, too:

```
[docs] [images:copy] /Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/configstore/index.js:86
[docs] [images:copy]   	return this.all[key];
[docs] [images:copy]   	               ^
[docs] [images:copy]
[docs] [images:copy] TypeError: Cannot read property 'update' of undefined
[docs] [images:copy]     at Object.Configstore.get (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/configstore/index.js:86:17)
[docs] [images:copy]     at UpdateNotifier.check (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/update-notifier/index.js:51:28)
[docs] [images:copy]     at module.exports (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/node_modules/update-notifier/index.js:127:17)
[docs] [images:copy]     at Object.<anonymous> (/Users/davidknezic/Repositories/style-guide/node_modules/sync-files/bin/sync-files.js:121:3)
[docs] [images:copy]     at Module._compile (module.js:413:34)
[docs] [images:copy]     at Object.Module._extensions..js (module.js:422:10)
[docs] [images:copy]     at Module.load (module.js:357:32)
[docs] [images:copy]     at Function.Module._load (module.js:314:12)
[docs] [images:copy]     at Function.Module.runMain (module.js:447:10)
[docs] [images:copy]     at startup (node.js:146:18)
```

**Comment by AndyOGo** [comment]
@davidknezic 
I had this `optOut` too

**Comment by AndyOGo** [comment]
Since it does not happen always.
I guess it could be a timing/orchestration problem

**Comment by AndyOGo** [comment]
Another one

````sh
[docs] [js:copy] /Users/axawinterthur/dev/style-guide/node_modules/configstore/index.js:86
[docs] [js:copy] 	return this.all[key];
[docs] [js:copy] 	               ^
[docs] [js:copy]
[docs] [js:copy] TypeError: Cannot read property 'lastUpdateCheck' of undefined
[docs] [js:copy]     at Object.Configstore.get (/Users/axawinterthur/dev/style-guide/node_modules/configstore/index.js:86:17)
[docs] [js:copy]     at UpdateNotifier.check (/Users/axawinterthur/dev/style-guide/node_modules/update-notifier/index.js:58:31)
[docs] [js:copy]     at module.exports (/Users/axawinterthur/dev/style-guide/node_modules/update-notifier/index.js:127:17)
[docs] [js:copy]     at Object.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/sync-files/bin/sync-files.js:121:3)
[docs] [js:copy]     at Module._compile (module.js:413:34)
[docs] [js:copy]     at Object.Module._extensions..js (module.js:422:10)
[docs] [js:copy]     at Module.load (module.js:357:32)
[docs] [js:copy]     at Function.Module._load (module.js:314:12)
[docs] [js:copy]     at Function.Module.runMain (module.js:447:10)
[docs] [js:copy]     at startup (node.js:146:18)
````

**Comment by AndyOGo** [comment]
Okidok, from what I see in the logs, all errors are related to our `sync-files` module.

**Comment by AndyOGo** [comment]
Okay, I'm sure I tracked it down 😄 
`sync-files` is using in it's binary version the `update-notifier` module, which is just tool meant to inform you (the CLI user) about an available upgrade, thats it, nothing more - go read the [about section](https://github.com/yeoman/update-notifier#about)

Because this update check is spawned into a new process, it should not affect our build.
Though I think we should create some issue inside `sync-files` module.

**Comment by AndyOGo** [comment]
@davidknezic @sventschui @elessar-ch 
Even if these bugs are not severe and should affect our build, but the fact that `nody-sync-files` [isn't actively maintained](https://github.com/byteclubfr/node-sync-files/graphs/contributors) makes me think to switch to antoher sync tool.

**Comment by TheDadi** [comment]
Im not fan of a heterogeneous environment, why not just let webpack do that for us? ☝🏻
