### ISSUE TITLE
Maven + Better-npm-run env vars lost

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#634]
If we kick-off our build with maven our environment variable of `NODE_ENV` is not considered.
To quickly fix it I had to hardcode it inside our `pom.xml`, like:

````xml
<configuration>
    <executable>node</executable>
    <environmentVariables>
        <BASE_URL>/src/</BASE_URL>
        <NODE_ENV>production</NODE_ENV>
    </environmentVariables>
    <arguments>
    	<argument>node_modules/gulp/bin/gulp.js</argument>
        <argument>build</argument>
        <argument>--harmony</argument>
    </arguments>
</configuration>
````

Any ideas?

I created an issue at https://github.com/benoror/better-npm-run/issues/53

**Comment by davidknezic** [comment]
shouldn't you execute `npm run something`?

**Comment by AndyOGo** [comment]
@davidknezic 
rooofl
That's my bad, I was so convinced that this maven stuff is utilizing `npm run build` I did not even look at it. Now that you are saying it ... I see it ... 😵

**Comment by AndyOGo** [comment]
clooooooossseeee
