### ISSUE TITLE
We need more icons!

### ISSUE THREAD

**Issue by davidknezic** [axa-ch/style-guide#65]
I went through some of our apps and made a list of necessary icons:
- [ ] user (or profile)
- [ ] group
- [x] calendar
- [ ] bookmark
- [ ] clock (or time)
- [ ] zoom in
- [ ] zoom out
- [x] information
- [ ] warning
- [x] loading indicator
- [x] search
- [x] download
- [ ] edit
- [ ] add
- [x] delete
- [x] check
- [ ] order ascending
- [ ] order descending

Add more as a comment...

**Comment by davidknezic** [comment]
:+1: 

We also need all the icons for the web site!!

**Comment by elessar-ch** [comment]
We'll design new Icons in the Relaunch Project. I think we should wait until they're done.
________________________________

**Comment by sventschui** [comment]
Closing because inactivity
