### ISSUE TITLE
Upload/File-List Actions static width causes overflow

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#694]
The width of `.file-uploaded__actions` is set to `158px`, this caused overflow if some text content is too long, which can easily happen for Italian or French translations.

![file_list_cancel_overflow](https://cloud.githubusercontent.com/assets/914443/20529182/9cc00274-b0cf-11e6-9d67-0774536bb20c.gif)

**Comment by AndyOGo** [comment]
btw it's not semamtic, only divs, no lists etc.

**Comment by davidknezic** [comment]
Do we even use that component anywhere?

**Comment by AndyOGo** [comment]
yes, in AEM forms ... for the files which will be uploaded.
