### ISSUE TITLE
Birthday datepicker days per month wrong

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/style-guide#723]
Currently our algorithm to generate days per month are not right.
Especially it is not true that every even-numbered month has `30` days and every odd-numbered month has `31` days - this affects June, July, August, December, etc.

https://github.com/axa-ch/style-guide/blob/develop/js/jquery/datepicker-birthday.js#L69

And the leap year is not considered:

https://github.com/axa-ch/style-guide/blob/develop/js/jquery/datepicker-birthday.js#L70

**Comment by sventschui** [comment]
Why the heck is this done on our own? I mean there are thousands of libs that handle this

**Comment by digisz** [comment]
rofl 🤣

**Comment by AndyOGo** [comment]
@sventschui 
This libs is even build in hehe

````js
new Date(2017, 2, 0).getDate(); // -> 28
new Date(2017, 12, 0).getDate(); // -> 31
````
